name: 'Airport Auto Get Traffic'

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 17 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade cloudscraper
    - name: 'Get traffic'
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        DOMAIN: ${{ vars.DOMAIN }}
      run: python airport_get_traffics.py
